version: '3'

services:
  app:
    image: docker
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
    - .src:/usr/src/app

  mongodb:
    image: mongo
    restart: always
    ports:
      - 2707:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  




    

